# Default properties file
spring:
  application:
    name: sample-api-voting-manager-java
  datasource:
    hikari:
      connection-timeout: '30000'
      pool-name: ${spring.application.name}
      idle-timeout: '600000'
      maximum-pool-size: '10'
      max-lifetime: '1800000'
      minimum-idle: '10'
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./db/voting_system;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;
    initialization-mode: always
    data: classpath:script.sql
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: '8080'
swagger:
  api:
    version: '@project.version@'
