CREATE SCHEMA IF NOT EXISTS VOTING_SYSTEM;

CREATE SEQUENCE IF NOT EXISTS VOTING_SYSTEM.SCHEDULE_SEQ;
CREATE SEQUENCE IF NOT EXISTS VOTING_SYSTEM.VOTING_SESSION_SEQ;
CREATE SEQUENCE IF NOT EXISTS VOTING_SYSTEM.VOTE_SEQ;

USE voting_system;

CREATE TABLE IF NOT EXISTS SCHEDULE (
    ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    USER_INCL VARCHAR(50) DEFAULT NULL,
	HOR_INCL TIMESTAMP DEFAULT NULL,
	USER_ALT VARCHAR(50) DEFAULT NULL,
	HOR_ALT TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS VOTING_SESSION (
    ID INT NOT NULL PRIMARY KEY,
    SCHEDULE_ID INT NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    USER_INCL VARCHAR(50) DEFAULT NULL,
	HOR_INCL TIMESTAMP DEFAULT NULL,
	USER_ALT VARCHAR(50) DEFAULT NULL,
	HOR_ALT TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID)
);

CREATE TABLE IF NOT EXISTS VOTE (
    ID INT NOT NULL PRIMARY KEY,
    SESSION_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    VOTE VARCHAR(255) NOT NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES VOTING_SESSION(ID)
);
